import type { Metadata } from 'next';
import type { FC } from 'react';
import { Footer } from '@/app/_components/Footer';
import { Header } from '@/app/_components/Header';

import '@/styles/globals.css';

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: {
    default: 'シンプルなコーポレートサイト',
    template: '%s | シンプルなコーポレートサイト',
  },
  description: 'Generated by create next app',
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="ja">
      <body className="">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
